# Generated by Django 4.2.20 on 2025-03-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.TextField(default='<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='calorie_goal',
            field=models.PositiveIntegerField(default=2000, help_text='Daily calorie goal'),
        ),
        migrations.AddField(
            model_name='user',
            name='step_goal',
            field=models.PositiveIntegerField(default=10000, help_text='Daily step goal'),
        ),
        migrations.AddField(
            model_name='user',
            name='workout_goal',
            field=models.PositiveIntegerField(default=3, help_text='Weekly workout goal'),
        ),
    ]
