# Generated by Django 4.2.20 on 2025-03-17 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('calories', models.FloatField(help_text='Calories per 100g')),
                ('protein', models.FloatField(help_text='Protein per 100g')),
                ('carbs', models.FloatField(help_text='Carbs per 100g')),
                ('fat', models.FloatField(help_text='Fat per 100g')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('lose weight', 'Lose Weight'), ('maintain', 'Maintain'), ('gain', 'Gain')], default='maintain', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.FloatField(help_text='Quantity in grams')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steps', models.PositiveIntegerField(default=0)),
                ('distance', models.FloatField(default=0, help_text='Distance in km')),
                ('time', models.PositiveIntegerField(default=0, help_text='Time in minutes')),
                ('calories_burned', models.FloatField(default=0, help_text='Calories burned')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BMIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('height', models.FloatField(help_text='Height in meters')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('bmi', models.FloatField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
